name: CI

on: [push]

jobs:
  build:
    runs-on: [windows-2016]

    steps:
    - uses: actions/checkout@v1
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.0.0
      with:
        toolset: 15.9
    - name: Build LuaEngine
      run: |
        cd LuaEngine
        msbuild -m /t:Build /p:Configuration=Release;Platform=Win64 LuaEngine.sln 
