name: CI

on: [push]

jobs:
  build:
    runs-on: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.0.0
    - name: Build LuaEngine
      run: |
        cd LuaEngine
        msbuild -m /t:Build /p:Configuration=Release;Platform=x64 LuaEngine.sln
        mv "LuaEngine/x64/Release/LuaEngine.dll" lua
        cd ..
    - name: GitHub Upload Release Artifacts
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            lua/*
           

